apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/name: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        resources:
          limits:
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: fluentbit-config
          mountPath: /fluent-bit/etc
      volumes:
      - name: fluentbit-config
        configMap:
          name: fluent-bit-config